### ISSUE TITLE
June rough work plan

### ISSUE THREAD

**Issue by cerasamson** [dotnet-interactive-learning/journey#3]
Long term
- [ ] Set up CI
- [ ] Liwam - close issue for individual coding assignment
- [ ] Angle - close issue for individual coding assignment
- [ ] Cera - close issue for individual coding assignment

Week of 6/14 to 6/18
- [x] Rough Hypothesis and questions
- [x] Meet with professor - gather/distribute findings, follow-up meeting with team
- [x] Refine hypothesis and questions
- [x] Meet with Maria
- [x] Refine hypothesis and questions [Projectideas.docx](https://microsoft-my.sharepoint.com/:w:/p/t-angleqian/Ec_DC2ufJUhHsmoGEaCiED0BolkHhBewS0u4tCpPrZmSSg?e=A499c6)
- [x] Schedule logistics for gather volunteer, conduct user study (schedule meeting/any logistics)
- [x] Refine student cohort
- [x] Determine user research structure, materials, what are the deliverables?
- [x] Create backup list of volunteers

Week 6/21 - 6/25
- [x] Deliverable before Tuesday: fleshed out research structure, organize all deliverables, perhaps except for sample notebooks, complete [UserStudy.docx](https://microsoft-my.sharepoint.com/:w:/p/t-cerasamson/ES1RQjwkj3BPvh0saIIwPBkB31k6F01HIErDlqUIFkYYjg?e=dyPkyc) document
- [x] Tuesday: meet with Giselle, detailed logistics for user research, get [UserStudy.docx](https://microsoft-my.sharepoint.com/:w:/p/t-cerasamson/ES1RQjwkj3BPvh0saIIwPBkB31k6F01HIErDlqUIFkYYjg?e=dyPkyc) document approved

Following week(s)
- [ ] Gather volunteers for user study (determine type of study, multiple rounds - students + prof.)
- [x] Develop user study (hypothesis / scenarios)
- [ ] Conducting user study
